"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var authRoutes_1 = require("./authRoutes");
var profileRoutes_1 = require("./profileRoutes");
var cropRoutes_1 = require("./cropRoutes");
var reportRoutes_1 = require("./reportRoutes");
var weatherRoutes_1 = require("./weatherRoutes");
var chatRoutes_1 = require("./chatRoutes");
var adminRoutes_1 = require("./adminRoutes");
var router = (0, express_1.Router)();
router.use('/auth', authRoutes_1.default);
router.use('/profile', profileRoutes_1.default);
router.use('/crops', cropRoutes_1.default);
router.use('/reports', reportRoutes_1.default);
router.use('/weather', weatherRoutes_1.default);
router.use('/chat', chatRoutes_1.default);
router.use('/admin', adminRoutes_1.default);
exports.default = router;
